### ISSUE TITLE
Request: Warn before an agent would die from being assigned to work on an abnormality

### ISSUE THREAD

**Issue by CTristan** [CTristan/lobotomy-corporation-mods#20]
Discovering how to deal with abnormalities is a major part of the game, however later on there are so many that have instakill abilities that are hard to keep track of. It's very annoying being almost done with a day with no deaths but then having an agent randomly die because either I forgot it had an instakill condition (like Crumbling Armor's gift and assigning Attachment work, or they just finished work on Fairy Festival), or it triggered because of a rare edge case (agent with Fortitude 3 sent to work on Singing Machine, they receive the gift which they gives them just enough Fortitude to increase it to 4, and they immediately die).

It would be nice to have a visual indicator that would tell me before I assign work that the agent will die if I send them.

**Comment by SabinStargem** [comment]
Hopefully the indicator comes online after mastering the abnormality, because it would be weird to know beforehand.   Maybe this feature could also approximate how much HP/SP is lost to a bad box?  That would have to take armor/gifts/tools into account, though.

This might be good to integrate together into a details mod package, to ensure compatibility?


The two detail mods I have, do the following...

*Indicate the work success rate by percentage, instead of vague terms.  The mods have different calculations, might not take into account creature mastery or gifts into the calculation.
*Shows how much XP for an virtue has been gained during the day.
*Articulates agent stats as numbers.
*Remaining number of virtue points to reach the next rank or the cap.  (Blacklights exclusive)
*Enemy healthbar.  Yentis's detail mod also adds numbers to the health bar.

**Comment by CTristan** [comment]
Very good point! It would be pretty spoilery to get a new abnormality and see half of your agents would die from doing Attachment work on it. It should only display the indication at full observation, to essentially require "mastery" of the abnormality.

I'll make sure it has compatibility with other detail mods but I believe it should be fine. My plan is to indicate with a red border in the assign work window, to make it visually stand out.
